// Code generated by protoc-gen-go. DO NOT EDIT.
// source: maintainer.proto

/*
Package maintainer is a generated protocol buffer package.

It is generated from these files:
	maintainer.proto

It has these top-level messages:
	RPCRecord
	RPCCausality
	RPCRecords
	RPCReply
	RPCBatchers
	RPCLId
	RPCRedisCache
*/
package maintainer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RPCRecord struct {
	Id        string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Timestamp int64             `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Host      uint32            `protobuf:"varint,3,opt,name=host" json:"host,omitempty"`
	Seqid     int64             `protobuf:"varint,4,opt,name=seqid" json:"seqid,omitempty"`
	Depth     uint32            `protobuf:"varint,5,opt,name=depth" json:"depth,omitempty"`
	Tags      map[string]string `protobuf:"bytes,6,rep,name=tags" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Trace     string            `protobuf:"bytes,7,opt,name=trace" json:"trace,omitempty"`
	// for TOID record
	Lid       uint32        `protobuf:"varint,8,opt,name=lid" json:"lid,omitempty"`
	Toid      uint32        `protobuf:"varint,9,opt,name=toid" json:"toid,omitempty"`
	Causality *RPCCausality `protobuf:"bytes,10,opt,name=causality" json:"causality,omitempty"`
}

func (m *RPCRecord) Reset()                    { *m = RPCRecord{} }
func (m *RPCRecord) String() string            { return proto.CompactTextString(m) }
func (*RPCRecord) ProtoMessage()               {}
func (*RPCRecord) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RPCRecord) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RPCRecord) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RPCRecord) GetHost() uint32 {
	if m != nil {
		return m.Host
	}
	return 0
}

func (m *RPCRecord) GetSeqid() int64 {
	if m != nil {
		return m.Seqid
	}
	return 0
}

func (m *RPCRecord) GetDepth() uint32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *RPCRecord) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *RPCRecord) GetTrace() string {
	if m != nil {
		return m.Trace
	}
	return ""
}

func (m *RPCRecord) GetLid() uint32 {
	if m != nil {
		return m.Lid
	}
	return 0
}

func (m *RPCRecord) GetToid() uint32 {
	if m != nil {
		return m.Toid
	}
	return 0
}

func (m *RPCRecord) GetCausality() *RPCCausality {
	if m != nil {
		return m.Causality
	}
	return nil
}

type RPCCausality struct {
	Host uint32 `protobuf:"varint,1,opt,name=host" json:"host,omitempty"`
	Toid uint32 `protobuf:"varint,2,opt,name=toid" json:"toid,omitempty"`
}

func (m *RPCCausality) Reset()                    { *m = RPCCausality{} }
func (m *RPCCausality) String() string            { return proto.CompactTextString(m) }
func (*RPCCausality) ProtoMessage()               {}
func (*RPCCausality) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RPCCausality) GetHost() uint32 {
	if m != nil {
		return m.Host
	}
	return 0
}

func (m *RPCCausality) GetToid() uint32 {
	if m != nil {
		return m.Toid
	}
	return 0
}

type RPCRecords struct {
	Records []*RPCRecord `protobuf:"bytes,1,rep,name=records" json:"records,omitempty"`
}

func (m *RPCRecords) Reset()                    { *m = RPCRecords{} }
func (m *RPCRecords) String() string            { return proto.CompactTextString(m) }
func (*RPCRecords) ProtoMessage()               {}
func (*RPCRecords) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RPCRecords) GetRecords() []*RPCRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

type RPCReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *RPCReply) Reset()                    { *m = RPCReply{} }
func (m *RPCReply) String() string            { return proto.CompactTextString(m) }
func (*RPCReply) ProtoMessage()               {}
func (*RPCReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RPCReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RPCBatchers struct {
	Version uint32   `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Batcher []string `protobuf:"bytes,2,rep,name=batcher" json:"batcher,omitempty"`
}

func (m *RPCBatchers) Reset()                    { *m = RPCBatchers{} }
func (m *RPCBatchers) String() string            { return proto.CompactTextString(m) }
func (*RPCBatchers) ProtoMessage()               {}
func (*RPCBatchers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RPCBatchers) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *RPCBatchers) GetBatcher() []string {
	if m != nil {
		return m.Batcher
	}
	return nil
}

type RPCLId struct {
	Lid uint32 `protobuf:"varint,1,opt,name=lid" json:"lid,omitempty"`
}

func (m *RPCLId) Reset()                    { *m = RPCLId{} }
func (m *RPCLId) String() string            { return proto.CompactTextString(m) }
func (*RPCLId) ProtoMessage()               {}
func (*RPCLId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RPCLId) GetLid() uint32 {
	if m != nil {
		return m.Lid
	}
	return 0
}

type RPCRedisCache struct {
	Version    uint32   `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	RedisCache []string `protobuf:"bytes,2,rep,name=redisCache" json:"redisCache,omitempty"`
}

func (m *RPCRedisCache) Reset()                    { *m = RPCRedisCache{} }
func (m *RPCRedisCache) String() string            { return proto.CompactTextString(m) }
func (*RPCRedisCache) ProtoMessage()               {}
func (*RPCRedisCache) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RPCRedisCache) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *RPCRedisCache) GetRedisCache() []string {
	if m != nil {
		return m.RedisCache
	}
	return nil
}

func init() {
	proto.RegisterType((*RPCRecord)(nil), "RPCRecord")
	proto.RegisterType((*RPCCausality)(nil), "RPCCausality")
	proto.RegisterType((*RPCRecords)(nil), "RPCRecords")
	proto.RegisterType((*RPCReply)(nil), "RPCReply")
	proto.RegisterType((*RPCBatchers)(nil), "RPCBatchers")
	proto.RegisterType((*RPCLId)(nil), "RPCLId")
	proto.RegisterType((*RPCRedisCache)(nil), "RPCRedisCache")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Maintainer service

type MaintainerClient interface {
	UpdateRedisCache(ctx context.Context, in *RPCRedisCache, opts ...grpc.CallOption) (*RPCReply, error)
	ReceiveRecords(ctx context.Context, in *RPCRecords, opts ...grpc.CallOption) (*RPCReply, error)
	UpdateBatchers(ctx context.Context, in *RPCBatchers, opts ...grpc.CallOption) (*RPCReply, error)
	TOIDReceiveRecords(ctx context.Context, in *RPCRecords, opts ...grpc.CallOption) (*RPCReply, error)
	TOIDUpdateBatchers(ctx context.Context, in *RPCBatchers, opts ...grpc.CallOption) (*RPCReply, error)
	TOIDReadByLId(ctx context.Context, in *RPCLId, opts ...grpc.CallOption) (*RPCReply, error)
}

type maintainerClient struct {
	cc *grpc.ClientConn
}

func NewMaintainerClient(cc *grpc.ClientConn) MaintainerClient {
	return &maintainerClient{cc}
}

func (c *maintainerClient) UpdateRedisCache(ctx context.Context, in *RPCRedisCache, opts ...grpc.CallOption) (*RPCReply, error) {
	out := new(RPCReply)
	err := grpc.Invoke(ctx, "/Maintainer/UpdateRedisCache", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerClient) ReceiveRecords(ctx context.Context, in *RPCRecords, opts ...grpc.CallOption) (*RPCReply, error) {
	out := new(RPCReply)
	err := grpc.Invoke(ctx, "/Maintainer/ReceiveRecords", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerClient) UpdateBatchers(ctx context.Context, in *RPCBatchers, opts ...grpc.CallOption) (*RPCReply, error) {
	out := new(RPCReply)
	err := grpc.Invoke(ctx, "/Maintainer/UpdateBatchers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerClient) TOIDReceiveRecords(ctx context.Context, in *RPCRecords, opts ...grpc.CallOption) (*RPCReply, error) {
	out := new(RPCReply)
	err := grpc.Invoke(ctx, "/Maintainer/TOIDReceiveRecords", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerClient) TOIDUpdateBatchers(ctx context.Context, in *RPCBatchers, opts ...grpc.CallOption) (*RPCReply, error) {
	out := new(RPCReply)
	err := grpc.Invoke(ctx, "/Maintainer/TOIDUpdateBatchers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *maintainerClient) TOIDReadByLId(ctx context.Context, in *RPCLId, opts ...grpc.CallOption) (*RPCReply, error) {
	out := new(RPCReply)
	err := grpc.Invoke(ctx, "/Maintainer/TOIDReadByLId", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Maintainer service

type MaintainerServer interface {
	UpdateRedisCache(context.Context, *RPCRedisCache) (*RPCReply, error)
	ReceiveRecords(context.Context, *RPCRecords) (*RPCReply, error)
	UpdateBatchers(context.Context, *RPCBatchers) (*RPCReply, error)
	TOIDReceiveRecords(context.Context, *RPCRecords) (*RPCReply, error)
	TOIDUpdateBatchers(context.Context, *RPCBatchers) (*RPCReply, error)
	TOIDReadByLId(context.Context, *RPCLId) (*RPCReply, error)
}

func RegisterMaintainerServer(s *grpc.Server, srv MaintainerServer) {
	s.RegisterService(&_Maintainer_serviceDesc, srv)
}

func _Maintainer_UpdateRedisCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCRedisCache)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServer).UpdateRedisCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Maintainer/UpdateRedisCache",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServer).UpdateRedisCache(ctx, req.(*RPCRedisCache))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maintainer_ReceiveRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCRecords)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServer).ReceiveRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Maintainer/ReceiveRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServer).ReceiveRecords(ctx, req.(*RPCRecords))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maintainer_UpdateBatchers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCBatchers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServer).UpdateBatchers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Maintainer/UpdateBatchers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServer).UpdateBatchers(ctx, req.(*RPCBatchers))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maintainer_TOIDReceiveRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCRecords)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServer).TOIDReceiveRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Maintainer/TOIDReceiveRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServer).TOIDReceiveRecords(ctx, req.(*RPCRecords))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maintainer_TOIDUpdateBatchers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCBatchers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServer).TOIDUpdateBatchers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Maintainer/TOIDUpdateBatchers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServer).TOIDUpdateBatchers(ctx, req.(*RPCBatchers))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maintainer_TOIDReadByLId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCLId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintainerServer).TOIDReadByLId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Maintainer/TOIDReadByLId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintainerServer).TOIDReadByLId(ctx, req.(*RPCLId))
	}
	return interceptor(ctx, in, info, handler)
}

var _Maintainer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Maintainer",
	HandlerType: (*MaintainerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateRedisCache",
			Handler:    _Maintainer_UpdateRedisCache_Handler,
		},
		{
			MethodName: "ReceiveRecords",
			Handler:    _Maintainer_ReceiveRecords_Handler,
		},
		{
			MethodName: "UpdateBatchers",
			Handler:    _Maintainer_UpdateBatchers_Handler,
		},
		{
			MethodName: "TOIDReceiveRecords",
			Handler:    _Maintainer_TOIDReceiveRecords_Handler,
		},
		{
			MethodName: "TOIDUpdateBatchers",
			Handler:    _Maintainer_TOIDUpdateBatchers_Handler,
		},
		{
			MethodName: "TOIDReadByLId",
			Handler:    _Maintainer_TOIDReadByLId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "maintainer.proto",
}

func init() { proto.RegisterFile("maintainer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 473 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x93, 0xdf, 0x6a, 0xdb, 0x30,
	0x14, 0xc6, 0x27, 0x3b, 0x4d, 0xea, 0x93, 0x26, 0x04, 0xd1, 0x0b, 0x11, 0xc6, 0x30, 0xa6, 0x03,
	0xb3, 0x82, 0x0b, 0x19, 0x6c, 0x63, 0x77, 0xab, 0xb7, 0x8b, 0xc0, 0xc6, 0x82, 0xe8, 0x1e, 0x40,
	0xb5, 0x44, 0x22, 0x96, 0xc4, 0x9e, 0xa4, 0x06, 0xfc, 0x32, 0x7b, 0x9b, 0xbd, 0xd7, 0x90, 0xe4,
	0x7f, 0xb9, 0x29, 0xbd, 0x3b, 0xe7, 0xe8, 0xcb, 0xf7, 0x7d, 0xf9, 0x91, 0xc0, 0xe2, 0xc0, 0xe4,
	0xd1, 0x30, 0x79, 0x14, 0x2a, 0xab, 0x54, 0x69, 0xca, 0xe4, 0x5f, 0x00, 0x11, 0xdd, 0xe4, 0x54,
	0x14, 0xa5, 0xe2, 0x78, 0x0e, 0x81, 0xe4, 0x04, 0xc5, 0x28, 0x8d, 0x68, 0x20, 0x39, 0x7e, 0x0d,
	0x91, 0x91, 0x07, 0xa1, 0x0d, 0x3b, 0x54, 0x24, 0x88, 0x51, 0x1a, 0xd2, 0xfe, 0x80, 0x31, 0x8c,
	0x76, 0xa5, 0x36, 0x24, 0x8c, 0x51, 0x3a, 0xa3, 0x6e, 0xc6, 0xd7, 0x70, 0xa1, 0xc5, 0x1f, 0xc9,
	0xc9, 0xc8, 0xa9, 0xfd, 0x62, 0xaf, 0x5c, 0x54, 0x66, 0x47, 0x2e, 0x9c, 0xd4, 0x2f, 0x38, 0x85,
	0x91, 0x61, 0x5b, 0x4d, 0xc6, 0x71, 0x98, 0x4e, 0x57, 0xd7, 0x59, 0xd7, 0x23, 0x7b, 0x60, 0x5b,
	0xfd, 0xed, 0x68, 0x54, 0x4d, 0x9d, 0xc2, 0x7e, 0xde, 0x28, 0x56, 0x08, 0x32, 0x71, 0xd5, 0xfc,
	0x82, 0x17, 0x10, 0xee, 0x25, 0x27, 0x97, 0xce, 0xd3, 0x8e, 0xb6, 0x91, 0x29, 0x25, 0x27, 0x91,
	0x6f, 0x64, 0x67, 0x7c, 0x0b, 0x51, 0xc1, 0x9e, 0x34, 0xdb, 0x4b, 0x53, 0x13, 0x88, 0x51, 0x3a,
	0x5d, 0xcd, 0x6c, 0x54, 0xde, 0x1e, 0x69, 0xff, 0xbe, 0xfc, 0x08, 0x51, 0x97, 0x6d, 0xfd, 0x7f,
	0x8b, 0xba, 0xc1, 0x61, 0x47, 0xdb, 0xe3, 0xc4, 0xf6, 0x4f, 0xc2, 0xb1, 0x88, 0xa8, 0x5f, 0x3e,
	0x07, 0x9f, 0x50, 0xf2, 0x01, 0xae, 0x86, 0x9e, 0x1d, 0x1b, 0x34, 0x60, 0xd3, 0xb6, 0x0b, 0xfa,
	0x76, 0xc9, 0x0a, 0xa0, 0xfb, 0xda, 0x1a, 0xdf, 0xc0, 0x44, 0xf9, 0x91, 0x20, 0x07, 0x05, 0x7a,
	0x28, 0xb4, 0x7d, 0x4a, 0x6e, 0xe0, 0xd2, 0x5d, 0xab, 0x7d, 0x8d, 0x09, 0x4c, 0x0e, 0x42, 0x6b,
	0xb6, 0x15, 0x4d, 0xcf, 0x76, 0x4d, 0xbe, 0xc0, 0x94, 0x6e, 0xf2, 0x7b, 0x66, 0x8a, 0x9d, 0x50,
	0xda, 0x0a, 0x4f, 0x42, 0x69, 0x59, 0x1e, 0x9b, 0x4e, 0xed, 0x6a, 0x5f, 0x1e, 0xbd, 0x8a, 0x04,
	0x71, 0x68, 0x2d, 0x9a, 0x35, 0x59, 0xc2, 0x98, 0x6e, 0xf2, 0xef, 0x6b, 0xde, 0xa2, 0x46, 0x1d,
	0xea, 0x64, 0x0d, 0x33, 0x57, 0x82, 0x4b, 0x9d, 0xb3, 0x62, 0x27, 0x9e, 0x09, 0x78, 0x03, 0xa0,
	0x3a, 0x5d, 0x93, 0x31, 0xb8, 0xac, 0xfe, 0x06, 0x00, 0x3f, 0xba, 0x1f, 0x26, 0xbe, 0x83, 0xc5,
	0xaf, 0x8a, 0x33, 0x23, 0x06, 0xe6, 0xf3, 0xec, 0x2c, 0x6c, 0x19, 0x65, 0x2d, 0x81, 0xe4, 0x15,
	0x7e, 0x07, 0x73, 0x2a, 0x0a, 0x21, 0x4f, 0xa2, 0xe5, 0x38, 0xed, 0xb1, 0xe9, 0x73, 0xed, 0x2d,
	0xcc, 0xbd, 0x79, 0x07, 0xe6, 0x2a, 0x1b, 0x60, 0x3a, 0x17, 0x67, 0x80, 0x1f, 0x7e, 0xae, 0xbf,
	0xbe, 0xd8, 0xfc, 0xce, 0xeb, 0x5f, 0x1e, 0xf0, 0x16, 0x66, 0x3e, 0x80, 0xf1, 0xfb, 0xda, 0x72,
	0x9e, 0x64, 0x1e, 0xf8, 0x99, 0xec, 0x71, 0xec, 0xfe, 0xab, 0xef, 0xff, 0x07, 0x00, 0x00, 0xff,
	0xff, 0xad, 0x35, 0xc1, 0x4c, 0xbf, 0x03, 0x00, 0x00,
}
