// Code generated by protoc-gen-go. DO NOT EDIT.
// source: maintainer/indexer/indexer.proto

/*
Package indexer is a generated protocol buffer package.

It is generated from these files:
	maintainer/indexer/indexer.proto

It has these top-level messages:
	RPCRecord
	RPCRecords
	RPCReply
	RPCQueries
	RPCQuery
	RPCQueryReply
	RPCTags
	RPCLIds
*/
package indexer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RPCRecord struct {
	Timestamp int64             `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Host      int32             `protobuf:"varint,2,opt,name=host" json:"host,omitempty"`
	Lid       int32             `protobuf:"varint,3,opt,name=lid" json:"lid,omitempty"`
	Tags      map[string]string `protobuf:"bytes,4,rep,name=tags" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Hash      []uint64          `protobuf:"varint,5,rep,packed,name=hash" json:"hash,omitempty"`
	Seed      uint64            `protobuf:"varint,6,opt,name=seed" json:"seed,omitempty"`
}

func (m *RPCRecord) Reset()                    { *m = RPCRecord{} }
func (m *RPCRecord) String() string            { return proto.CompactTextString(m) }
func (*RPCRecord) ProtoMessage()               {}
func (*RPCRecord) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RPCRecord) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RPCRecord) GetHost() int32 {
	if m != nil {
		return m.Host
	}
	return 0
}

func (m *RPCRecord) GetLid() int32 {
	if m != nil {
		return m.Lid
	}
	return 0
}

func (m *RPCRecord) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *RPCRecord) GetHash() []uint64 {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *RPCRecord) GetSeed() uint64 {
	if m != nil {
		return m.Seed
	}
	return 0
}

type RPCRecords struct {
	Records []*RPCRecord `protobuf:"bytes,1,rep,name=records" json:"records,omitempty"`
}

func (m *RPCRecords) Reset()                    { *m = RPCRecords{} }
func (m *RPCRecords) String() string            { return proto.CompactTextString(m) }
func (*RPCRecords) ProtoMessage()               {}
func (*RPCRecords) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RPCRecords) GetRecords() []*RPCRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

type RPCReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *RPCReply) Reset()                    { *m = RPCReply{} }
func (m *RPCReply) String() string            { return proto.CompactTextString(m) }
func (*RPCReply) ProtoMessage()               {}
func (*RPCReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RPCReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RPCQueries struct {
	Queries []*RPCQuery `protobuf:"bytes,1,rep,name=queries" json:"queries,omitempty"`
}

func (m *RPCQueries) Reset()                    { *m = RPCQueries{} }
func (m *RPCQueries) String() string            { return proto.CompactTextString(m) }
func (*RPCQueries) ProtoMessage()               {}
func (*RPCQueries) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RPCQueries) GetQueries() []*RPCQuery {
	if m != nil {
		return m.Queries
	}
	return nil
}

type RPCQuery struct {
	Hash []uint64 `protobuf:"varint,1,rep,packed,name=hash" json:"hash,omitempty"`
	Seed uint64   `protobuf:"varint,2,opt,name=seed" json:"seed,omitempty"`
}

func (m *RPCQuery) Reset()                    { *m = RPCQuery{} }
func (m *RPCQuery) String() string            { return proto.CompactTextString(m) }
func (*RPCQuery) ProtoMessage()               {}
func (*RPCQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RPCQuery) GetHash() []uint64 {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *RPCQuery) GetSeed() uint64 {
	if m != nil {
		return m.Seed
	}
	return 0
}

type RPCQueryReply struct {
	Reply []bool `protobuf:"varint,1,rep,packed,name=reply" json:"reply,omitempty"`
}

func (m *RPCQueryReply) Reset()                    { *m = RPCQueryReply{} }
func (m *RPCQueryReply) String() string            { return proto.CompactTextString(m) }
func (*RPCQueryReply) ProtoMessage()               {}
func (*RPCQueryReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RPCQueryReply) GetReply() []bool {
	if m != nil {
		return m.Reply
	}
	return nil
}

type RPCTags struct {
	Lid  int32             `protobuf:"varint,1,opt,name=lid" json:"lid,omitempty"`
	Seed uint64            `protobuf:"varint,2,opt,name=seed" json:"seed,omitempty"`
	Tags map[string]string `protobuf:"bytes,3,rep,name=tags" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *RPCTags) Reset()                    { *m = RPCTags{} }
func (m *RPCTags) String() string            { return proto.CompactTextString(m) }
func (*RPCTags) ProtoMessage()               {}
func (*RPCTags) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RPCTags) GetLid() int32 {
	if m != nil {
		return m.Lid
	}
	return 0
}

func (m *RPCTags) GetSeed() uint64 {
	if m != nil {
		return m.Seed
	}
	return 0
}

func (m *RPCTags) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type RPCLIds struct {
	Lid []int32 `protobuf:"varint,1,rep,packed,name=lid" json:"lid,omitempty"`
}

func (m *RPCLIds) Reset()                    { *m = RPCLIds{} }
func (m *RPCLIds) String() string            { return proto.CompactTextString(m) }
func (*RPCLIds) ProtoMessage()               {}
func (*RPCLIds) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RPCLIds) GetLid() []int32 {
	if m != nil {
		return m.Lid
	}
	return nil
}

func init() {
	proto.RegisterType((*RPCRecord)(nil), "RPCRecord")
	proto.RegisterType((*RPCRecords)(nil), "RPCRecords")
	proto.RegisterType((*RPCReply)(nil), "RPCReply")
	proto.RegisterType((*RPCQueries)(nil), "RPCQueries")
	proto.RegisterType((*RPCQuery)(nil), "RPCQuery")
	proto.RegisterType((*RPCQueryReply)(nil), "RPCQueryReply")
	proto.RegisterType((*RPCTags)(nil), "RPCTags")
	proto.RegisterType((*RPCLIds)(nil), "RPCLIds")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Indexer service

type IndexerClient interface {
	Query(ctx context.Context, in *RPCQueries, opts ...grpc.CallOption) (*RPCQueryReply, error)
	InsertTags(ctx context.Context, in *RPCTags, opts ...grpc.CallOption) (*RPCReply, error)
	GetLIds(ctx context.Context, in *RPCTags, opts ...grpc.CallOption) (*RPCLIds, error)
}

type indexerClient struct {
	cc *grpc.ClientConn
}

func NewIndexerClient(cc *grpc.ClientConn) IndexerClient {
	return &indexerClient{cc}
}

func (c *indexerClient) Query(ctx context.Context, in *RPCQueries, opts ...grpc.CallOption) (*RPCQueryReply, error) {
	out := new(RPCQueryReply)
	err := grpc.Invoke(ctx, "/Indexer/Query", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexerClient) InsertTags(ctx context.Context, in *RPCTags, opts ...grpc.CallOption) (*RPCReply, error) {
	out := new(RPCReply)
	err := grpc.Invoke(ctx, "/Indexer/InsertTags", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexerClient) GetLIds(ctx context.Context, in *RPCTags, opts ...grpc.CallOption) (*RPCLIds, error) {
	out := new(RPCLIds)
	err := grpc.Invoke(ctx, "/Indexer/GetLIds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Indexer service

type IndexerServer interface {
	Query(context.Context, *RPCQueries) (*RPCQueryReply, error)
	InsertTags(context.Context, *RPCTags) (*RPCReply, error)
	GetLIds(context.Context, *RPCTags) (*RPCLIds, error)
}

func RegisterIndexerServer(s *grpc.Server, srv IndexerServer) {
	s.RegisterService(&_Indexer_serviceDesc, srv)
}

func _Indexer_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCQueries)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexerServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Indexer/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexerServer).Query(ctx, req.(*RPCQueries))
	}
	return interceptor(ctx, in, info, handler)
}

func _Indexer_InsertTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCTags)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexerServer).InsertTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Indexer/InsertTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexerServer).InsertTags(ctx, req.(*RPCTags))
	}
	return interceptor(ctx, in, info, handler)
}

func _Indexer_GetLIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCTags)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexerServer).GetLIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Indexer/GetLIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexerServer).GetLIds(ctx, req.(*RPCTags))
	}
	return interceptor(ctx, in, info, handler)
}

var _Indexer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Indexer",
	HandlerType: (*IndexerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _Indexer_Query_Handler,
		},
		{
			MethodName: "InsertTags",
			Handler:    _Indexer_InsertTags_Handler,
		},
		{
			MethodName: "GetLIds",
			Handler:    _Indexer_GetLIds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "maintainer/indexer/indexer.proto",
}

func init() { proto.RegisterFile("maintainer/indexer/indexer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0xce, 0xd3, 0x30,
	0x10, 0xad, 0x9b, 0xe4, 0x4b, 0x33, 0x9f, 0x40, 0xc8, 0xea, 0xc2, 0x2a, 0x48, 0x44, 0x6e, 0xa9,
	0xb2, 0x32, 0x22, 0x2c, 0x40, 0x6c, 0x2b, 0x84, 0x2a, 0xb1, 0x28, 0x16, 0x17, 0x30, 0xc4, 0x6a,
	0x23, 0x9a, 0xa4, 0xd8, 0x2e, 0x90, 0x5b, 0x70, 0x3e, 0x4e, 0x83, 0x3c, 0xf9, 0x03, 0xd4, 0x15,
	0xab, 0xbc, 0x79, 0x93, 0x79, 0xf3, 0x66, 0xc6, 0x90, 0x56, 0xaa, 0xac, 0x9d, 0x2a, 0x6b, 0x6d,
	0x9e, 0x97, 0x75, 0xa1, 0x7f, 0x4c, 0x5f, 0x71, 0x31, 0x8d, 0x6b, 0xf8, 0x2f, 0x02, 0x89, 0x3c,
	0xec, 0xa4, 0xfe, 0xdc, 0x98, 0x82, 0x3e, 0x81, 0xc4, 0x95, 0x95, 0xb6, 0x4e, 0x55, 0x17, 0x46,
	0x52, 0x92, 0x05, 0x72, 0x22, 0x28, 0x85, 0xf0, 0xd4, 0x58, 0xc7, 0xe6, 0x29, 0xc9, 0x22, 0x89,
	0x98, 0x3e, 0x82, 0xe0, 0x5c, 0x16, 0x2c, 0x40, 0xca, 0x43, 0x9a, 0x41, 0xe8, 0xd4, 0xd1, 0xb2,
	0x30, 0x0d, 0xb2, 0xfb, 0x7c, 0x29, 0x46, 0x75, 0xf1, 0x51, 0x1d, 0xed, 0xdb, 0xda, 0x99, 0x56,
	0xe2, 0x1f, 0xa8, 0xa7, 0xec, 0x89, 0x45, 0x69, 0x90, 0x85, 0x12, 0xb1, 0xe7, 0xac, 0xd6, 0x05,
	0xbb, 0x4b, 0x89, 0xe7, 0x3c, 0x5e, 0xbd, 0x82, 0x64, 0x2c, 0xf5, 0x0d, 0xbf, 0xe8, 0x16, 0xcd,
	0x25, 0xd2, 0x43, 0xba, 0x84, 0xe8, 0x9b, 0x3a, 0x5f, 0x35, 0xfa, 0x4a, 0x64, 0x17, 0xbc, 0x99,
	0xbf, 0x26, 0x3c, 0x07, 0x18, 0xbb, 0x5b, 0xba, 0x81, 0xd8, 0x74, 0x90, 0x11, 0xf4, 0x06, 0x93,
	0x37, 0x39, 0xa4, 0xf8, 0x06, 0x16, 0xc8, 0x5e, 0xce, 0x2d, 0x65, 0x10, 0x57, 0xda, 0x5a, 0x75,
	0xd4, 0x7d, 0xbf, 0x21, 0xe4, 0x2f, 0x50, 0xf9, 0xc3, 0x55, 0x9b, 0x52, 0x5b, 0xba, 0x86, 0xf8,
	0x6b, 0x07, 0x7b, 0xe5, 0x44, 0xf4, 0xd9, 0x56, 0x0e, 0x19, 0x9e, 0xa3, 0x30, 0x92, 0xe3, 0xe4,
	0xe4, 0xc6, 0xe4, 0xf3, 0x69, 0x72, 0xfe, 0x0c, 0x1e, 0x8c, 0x42, 0xe8, 0x68, 0x09, 0x91, 0xf1,
	0x00, 0x2b, 0x17, 0xb2, 0x0b, 0xf8, 0x4f, 0x02, 0xb1, 0x3c, 0xec, 0xfc, 0x92, 0x86, 0x83, 0x90,
	0xe9, 0x20, 0x37, 0x84, 0xe9, 0xb6, 0x3f, 0x52, 0x80, 0x76, 0xa9, 0xe8, 0xab, 0xff, 0x3d, 0xd1,
	0xff, 0xaf, 0xfe, 0x31, 0x3a, 0x7a, 0xbf, 0x2f, 0xfe, 0x70, 0x14, 0xf4, 0x8e, 0xf2, 0xef, 0x10,
	0xef, 0xbb, 0x57, 0x48, 0xb7, 0x10, 0x75, 0x2b, 0xb9, 0x17, 0xd3, 0x42, 0x57, 0x0f, 0xc5, 0x5f,
	0x63, 0xf3, 0x19, 0x5d, 0x03, 0xec, 0x6b, 0xab, 0x8d, 0xc3, 0x21, 0x17, 0x83, 0xe1, 0x55, 0x22,
	0x86, 0x6b, 0xf1, 0x19, 0x7d, 0x0a, 0xf1, 0x3b, 0xed, 0xb0, 0xe9, 0xf4, 0x07, 0x22, 0xcf, 0xf1,
	0xd9, 0xa7, 0x3b, 0x7c, 0xf4, 0x2f, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x59, 0x33, 0x3e, 0xe5,
	0x18, 0x03, 0x00, 0x00,
}
