version: '3'
services:
  controller:
    image: fasthall/gochariots
    entrypoint: gochariots controller -p 8081 -d
    volumes:
      - ./logs:/go/logs
    ports: 
      - 8081:8081
    networks:
      - cluster
  app:
    image: fasthall/gochariots
    entrypoint: gochariots app -p 8080 -d -f config/config.yaml
    depends_on:
      - controller
    volumes:
      - ./config:/go/config
      - ./logs:/go/logs
    depends_on:
      - controller
    ports:
      - 8080:8080
    networks:
      - cluster
  batcher:
    image: fasthall/gochariots
    entrypoint: gochariots batcher -p 9000 -d -f config/config.yaml
    depends_on:
      - controller
    volumes:
      - ./config:/go/config
      - ./logs:/go/logs
    ports: 
      - 9000
    environment:
      - TCP_PORTS=9000
    networks:
      - cluster
  queue-leader:
    image: fasthall/gochariots
    entrypoint: gochariots queue --hold -d -f config/config.yaml
    depends_on:
      - controller
    volumes:
      - ./config:/go/config
      - ./logs:/go/logs
    networks:
      - cluster
  queue:
    image: fasthall/gochariots
    entrypoint: gochariots queue --no-hold -d -f config/config.yaml
    depends_on:
      - controller
    volumes:
      - ./config:/go/config
      - ./logs:/go/logs
    networks:
      - cluster
  maintainer:
    image: fasthall/gochariots
    entrypoint: gochariots maintainer -d -f config/config.yaml --datastore
    environment:
      - DATASTORE_PROJECT_ID=your_gcp_project_id
      - GOOGLE_APPLICATION_CREDENTIALS=/go/cred/cred.json
    depends_on:
      - controller
    volumes:
      - ./config:/go/config
      - ./logs:/go/logs
      - ./flstore:/go/flstore
      - ./cred:/go/cred
    networks:
      - cluster
  indexer:
    image: fasthall/gochariots
    entrypoint: gochariots indexer -d -f config/config.yaml
    depends_on:
      - controller
    volumes:
      - ./config:/go/config
      - ./logs:/go/logs
    networks:
      - cluster
  batcher_lb:
    image: dockercloud/haproxy
    depends_on:
      - batcher
    ports:
      - 9000:9000
    links:
      - batcher
    networks:                                                                                                                                  
      - cluster
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  cluster:
