version: '3'
services:
  controller:
    image: fasthall/gochariots
    entrypoint: gochariots controller -p 8081 1 0 -i
    volumes:
      - /home/ubuntu/deploy/logs:/go/logs
    depends_on:
      - controller
    ports: 
      - 8081:8081
    networks:
      - cluster
  app:
    image: fasthall/gochariots
    entrypoint: gochariots app -p 8080 1 0 -i -f config/config.yaml
    volumes:
      - /home/ubuntu/deploy/config:/go/config
      - /home/ubuntu/deploy/logs:/go/logs
    depends_on:
      - controller
    ports:
      - 8080:8080
    networks:
      - cluster
  batcher:
    image: fasthall/gochariots
    entrypoint: gochariots batcher -p 9000 1 0 -i -f config/config.yaml
    volumes:
      - /home/ubuntu/deploy/config:/go/config
      - /home/ubuntu/deploy/logs:/go/logs
    depends_on:
      - controller
    environment:
      - TCP_PORTS=9000
      - SERVICE_PORTS=9000
    deploy:
      replicas: 3
    networks:
      - cluster
  filter:
    image: fasthall/gochariots
    entrypoint: gochariots filter 1 0 -i -f config/config.yaml
    volumes:
      - /home/ubuntu/deploy/config:/go/config
      - /home/ubuntu/deploy/logs:/go/logs
    depends_on:
      - controller
    networks:
      - cluster
  queue-leader:
    image: fasthall/gochariots
    entrypoint: gochariots queue --hold 1 0 -i -f config/config.yaml
    volumes:
      - /home/ubuntu/deploy/config:/go/config
      - /home/ubuntu/deploy/logs:/go/logs
    depends_on:
      - controller
    networks:
      - cluster
  queue:
    image: fasthall/gochariots
    entrypoint: gochariots queue --no-hold 1 0 -i -f config/config.yaml
    volumes:
      - /home/ubuntu/deploy/config:/go/config
      - /home/ubuntu/deploy/logs:/go/logs
    depends_on:
      - controller
    networks:
      - cluster
  maintainer:
    image: fasthall/gochariots
    entrypoint: gochariots maintainer 1 0 -i -f config/config.yaml
    volumes:
      - /home/ubuntu/deploy/config:/go/config
      - /home/ubuntu/deploy/logs:/go/logs
      - /home/ubuntu/deploy/flstore:/go/flstore
    depends_on:
      - controller
    networks:
      - cluster
  indexer:
    image: fasthall/gochariots
    entrypoint: gochariots indexer 1 0 -i -f config/config.yaml
    volumes:
      - /home/ubuntu/deploy/config:/go/config
      - /home/ubuntu/deploy/logs:/go/logs
    depends_on:
      - controller
    networks:
      - cluster
  batcher_lb:
    image: dockercloud/haproxy
    ports:
      - 9000:9000
    links:
      - batcher
    networks:                                                                                                                                  
      - cluster
    depends_on:
      - batcher
      - controller
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  cluster:
