version: '3'
services:
  app:
    image: fasthall/gochariots
    entrypoint: gochariots app -p app_port -i -f config/config.yaml
    volumes:
      - ./config:/go/config
      - ./logs:/go/logs
    ports: 
      - app_port:app_port
    networks:
      - cluster
    deploy:
      placement:
        constraints:
          - node.role == manager
  controller:
    image: fasthall/gochariots
    entrypoint: gochariots controller -p controller_port -i
    volumes:
      - ./logs:/go/logs
    ports: 
      - controller_port:controller_port
    networks:
      - cluster
  batcher:
    image: fasthall/gochariots
    entrypoint: gochariots batcher -p batcher_port -f config/config.yaml -i --buffer_size=10000 --benchmark_accuracy 10000
    depends_on:
      - controller
    volumes:
      - ./config:/go/config
      - ./logs:/go/logs
    ports: 
      - batcher_port
    environment:
      - TCP_PORTS=batcher_port
      - SERVICE_PORTS=batcher_port
    networks:
      - cluster
    deploy:
      placement:
        constraints:
          - node.role == manager
  queue-leader:
    image: fasthall/gochariots
    entrypoint: gochariots queue --hold -f config/config.yaml -i --benchmark_accuracy 10000
    depends_on:
      - queue
      - controller
    volumes:
      - ./config:/go/config
      - ./logs:/go/logs
    networks:
      - cluster
  queue:
    image: fasthall/gochariots
    entrypoint: gochariots queue --no-hold -f config/config.yaml -i --benchmark_accuracy 10000
    depends_on:
      - controller
    volumes:
      - ./config:/go/config
      - ./logs:/go/logs
    networks:
      - cluster
  maintainer:
    image: fasthall/gochariots
    entrypoint: gochariots maintainer -f config/config.yaml -i --mongodb --benchmark_accuracy 10000
    depends_on:
      - controller
    volumes:
      - ./config:/go/config
      - ./logs:/go/logs
    networks:
      - cluster
  storage:
    image: fasthall/mongo-for-lowgo
    entrypoint: docker-entrypoint.sh
    depends_on:
    - controller
    volumes:
    - ./config:/config
    ports:
    - storage_port:storage_port
    networks:
    - cluster
  batcher_lb:
    image: dockercloud/haproxy
    depends_on:
      - batcher
    ports:
      - batcher_lb_port:batcher_lb_port
    links:
      - batcher
    networks:                                                                                                                                  
      - cluster
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  cache:
    image: fasthall/redis-cache-for-lowgo
    entrypoint: docker-entrypoint.sh
    depends_on:
      - controller
    volumes:
      - ./config:/config
    ports:
      - cache_port:cache_port
    networks:
      - cluster
networks:
  cluster: