# -*- mode: ruby -*-                                                            
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  $script = <<-SCRIPT
  mkdir /home/vagrant/go
  go get -v github.com/fasthall/gochariots/cmd/...
  echo export PATH=$PATH:$HOME/go/bin >> $HOME/.profile
  SCRIPT

  config.vm.box = "comnets/mininet"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y vim curl
    wget https://storage.googleapis.com/golang/go1.8.linux-amd64.tar.gz /home/vagrant/go1.8.linux-amd64.tar.gz
    tar -C /usr/local -xzf go1.8.linux-amd64.tar.gz
    echo export PATH=$PATH:/usr/local/go/bin >> /etc/profile
  SHELL
    config.vm.provision "shell", inline: $script, privileged: false
end