// Code generated by protoc-gen-go. DO NOT EDIT.
// source: queue/queue.proto

/*
Package queue is a generated protocol buffer package.

It is generated from these files:
	queue/queue.proto

It has these top-level messages:
	RPCRecord
	RPCCausality
	RPCRecords
	RPCReply
	RPCQueue
	RPCToken
	RPCMaintainers
	RPCIndexers
	RPCTOIDToken
*/
package queue

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RPCRecord struct {
	Id        string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Timestamp int64             `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Host      uint32            `protobuf:"varint,3,opt,name=host" json:"host,omitempty"`
	Lid       uint32            `protobuf:"varint,4,opt,name=lid" json:"lid,omitempty"`
	Tags      map[string]string `protobuf:"bytes,5,rep,name=tags" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Parent    []string          `protobuf:"bytes,6,rep,name=parent" json:"parent,omitempty"`
	Seed      string            `protobuf:"bytes,7,opt,name=seed" json:"seed,omitempty"`
	// for TOID record
	Toid      uint32        `protobuf:"varint,8,opt,name=toid" json:"toid,omitempty"`
	Causality *RPCCausality `protobuf:"bytes,9,opt,name=causality" json:"causality,omitempty"`
}

func (m *RPCRecord) Reset()                    { *m = RPCRecord{} }
func (m *RPCRecord) String() string            { return proto.CompactTextString(m) }
func (*RPCRecord) ProtoMessage()               {}
func (*RPCRecord) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RPCRecord) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RPCRecord) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RPCRecord) GetHost() uint32 {
	if m != nil {
		return m.Host
	}
	return 0
}

func (m *RPCRecord) GetLid() uint32 {
	if m != nil {
		return m.Lid
	}
	return 0
}

func (m *RPCRecord) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *RPCRecord) GetParent() []string {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *RPCRecord) GetSeed() string {
	if m != nil {
		return m.Seed
	}
	return ""
}

func (m *RPCRecord) GetToid() uint32 {
	if m != nil {
		return m.Toid
	}
	return 0
}

func (m *RPCRecord) GetCausality() *RPCCausality {
	if m != nil {
		return m.Causality
	}
	return nil
}

type RPCCausality struct {
	Host uint32 `protobuf:"varint,1,opt,name=host" json:"host,omitempty"`
	Toid uint32 `protobuf:"varint,2,opt,name=toid" json:"toid,omitempty"`
}

func (m *RPCCausality) Reset()                    { *m = RPCCausality{} }
func (m *RPCCausality) String() string            { return proto.CompactTextString(m) }
func (*RPCCausality) ProtoMessage()               {}
func (*RPCCausality) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RPCCausality) GetHost() uint32 {
	if m != nil {
		return m.Host
	}
	return 0
}

func (m *RPCCausality) GetToid() uint32 {
	if m != nil {
		return m.Toid
	}
	return 0
}

type RPCRecords struct {
	Records []*RPCRecord `protobuf:"bytes,1,rep,name=records" json:"records,omitempty"`
}

func (m *RPCRecords) Reset()                    { *m = RPCRecords{} }
func (m *RPCRecords) String() string            { return proto.CompactTextString(m) }
func (*RPCRecords) ProtoMessage()               {}
func (*RPCRecords) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RPCRecords) GetRecords() []*RPCRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

type RPCReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *RPCReply) Reset()                    { *m = RPCReply{} }
func (m *RPCReply) String() string            { return proto.CompactTextString(m) }
func (*RPCReply) ProtoMessage()               {}
func (*RPCReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RPCReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RPCQueue struct {
	Version uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Queue   string `protobuf:"bytes,2,opt,name=queue" json:"queue,omitempty"`
}

func (m *RPCQueue) Reset()                    { *m = RPCQueue{} }
func (m *RPCQueue) String() string            { return proto.CompactTextString(m) }
func (*RPCQueue) ProtoMessage()               {}
func (*RPCQueue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RPCQueue) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *RPCQueue) GetQueue() string {
	if m != nil {
		return m.Queue
	}
	return ""
}

type RPCToken struct {
	Lastlid uint32 `protobuf:"varint,1,opt,name=lastlid" json:"lastlid,omitempty"`
}

func (m *RPCToken) Reset()                    { *m = RPCToken{} }
func (m *RPCToken) String() string            { return proto.CompactTextString(m) }
func (*RPCToken) ProtoMessage()               {}
func (*RPCToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RPCToken) GetLastlid() uint32 {
	if m != nil {
		return m.Lastlid
	}
	return 0
}

type RPCMaintainers struct {
	Version    uint32   `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Maintainer []string `protobuf:"bytes,2,rep,name=maintainer" json:"maintainer,omitempty"`
}

func (m *RPCMaintainers) Reset()                    { *m = RPCMaintainers{} }
func (m *RPCMaintainers) String() string            { return proto.CompactTextString(m) }
func (*RPCMaintainers) ProtoMessage()               {}
func (*RPCMaintainers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RPCMaintainers) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *RPCMaintainers) GetMaintainer() []string {
	if m != nil {
		return m.Maintainer
	}
	return nil
}

type RPCIndexers struct {
	Version uint32   `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Indexer []string `protobuf:"bytes,2,rep,name=indexer" json:"indexer,omitempty"`
}

func (m *RPCIndexers) Reset()                    { *m = RPCIndexers{} }
func (m *RPCIndexers) String() string            { return proto.CompactTextString(m) }
func (*RPCIndexers) ProtoMessage()               {}
func (*RPCIndexers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RPCIndexers) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *RPCIndexers) GetIndexer() []string {
	if m != nil {
		return m.Indexer
	}
	return nil
}

type RPCTOIDToken struct {
	MaxTOId         []uint32     `protobuf:"varint,1,rep,packed,name=maxTOId" json:"maxTOId,omitempty"`
	LastLId         uint32       `protobuf:"varint,2,opt,name=lastLId" json:"lastLId,omitempty"`
	DeferredRecords []*RPCRecord `protobuf:"bytes,3,rep,name=deferredRecords" json:"deferredRecords,omitempty"`
}

func (m *RPCTOIDToken) Reset()                    { *m = RPCTOIDToken{} }
func (m *RPCTOIDToken) String() string            { return proto.CompactTextString(m) }
func (*RPCTOIDToken) ProtoMessage()               {}
func (*RPCTOIDToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RPCTOIDToken) GetMaxTOId() []uint32 {
	if m != nil {
		return m.MaxTOId
	}
	return nil
}

func (m *RPCTOIDToken) GetLastLId() uint32 {
	if m != nil {
		return m.LastLId
	}
	return 0
}

func (m *RPCTOIDToken) GetDeferredRecords() []*RPCRecord {
	if m != nil {
		return m.DeferredRecords
	}
	return nil
}

func init() {
	proto.RegisterType((*RPCRecord)(nil), "RPCRecord")
	proto.RegisterType((*RPCCausality)(nil), "RPCCausality")
	proto.RegisterType((*RPCRecords)(nil), "RPCRecords")
	proto.RegisterType((*RPCReply)(nil), "RPCReply")
	proto.RegisterType((*RPCQueue)(nil), "RPCQueue")
	proto.RegisterType((*RPCToken)(nil), "RPCToken")
	proto.RegisterType((*RPCMaintainers)(nil), "RPCMaintainers")
	proto.RegisterType((*RPCIndexers)(nil), "RPCIndexers")
	proto.RegisterType((*RPCTOIDToken)(nil), "RPCTOIDToken")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Queue service

type QueueClient interface {
	ReceiveRecords(ctx context.Context, in *RPCRecords, opts ...grpc.CallOption) (*RPCReply, error)
	ReceiveToken(ctx context.Context, in *RPCToken, opts ...grpc.CallOption) (*RPCReply, error)
	UpdateNextQueue(ctx context.Context, in *RPCQueue, opts ...grpc.CallOption) (*RPCReply, error)
	UpdateMaintainers(ctx context.Context, in *RPCMaintainers, opts ...grpc.CallOption) (*RPCReply, error)
	TOIDReceiveRecords(ctx context.Context, in *RPCRecords, opts ...grpc.CallOption) (*RPCReply, error)
	TOIDReceiveToken(ctx context.Context, in *RPCTOIDToken, opts ...grpc.CallOption) (*RPCReply, error)
	TOIDUpdateNextQueue(ctx context.Context, in *RPCQueue, opts ...grpc.CallOption) (*RPCReply, error)
	TOIDUpdateMaintainers(ctx context.Context, in *RPCMaintainers, opts ...grpc.CallOption) (*RPCReply, error)
}

type queueClient struct {
	cc *grpc.ClientConn
}

func NewQueueClient(cc *grpc.ClientConn) QueueClient {
	return &queueClient{cc}
}

func (c *queueClient) ReceiveRecords(ctx context.Context, in *RPCRecords, opts ...grpc.CallOption) (*RPCReply, error) {
	out := new(RPCReply)
	err := grpc.Invoke(ctx, "/Queue/ReceiveRecords", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueClient) ReceiveToken(ctx context.Context, in *RPCToken, opts ...grpc.CallOption) (*RPCReply, error) {
	out := new(RPCReply)
	err := grpc.Invoke(ctx, "/Queue/ReceiveToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueClient) UpdateNextQueue(ctx context.Context, in *RPCQueue, opts ...grpc.CallOption) (*RPCReply, error) {
	out := new(RPCReply)
	err := grpc.Invoke(ctx, "/Queue/UpdateNextQueue", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueClient) UpdateMaintainers(ctx context.Context, in *RPCMaintainers, opts ...grpc.CallOption) (*RPCReply, error) {
	out := new(RPCReply)
	err := grpc.Invoke(ctx, "/Queue/UpdateMaintainers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueClient) TOIDReceiveRecords(ctx context.Context, in *RPCRecords, opts ...grpc.CallOption) (*RPCReply, error) {
	out := new(RPCReply)
	err := grpc.Invoke(ctx, "/Queue/TOIDReceiveRecords", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueClient) TOIDReceiveToken(ctx context.Context, in *RPCTOIDToken, opts ...grpc.CallOption) (*RPCReply, error) {
	out := new(RPCReply)
	err := grpc.Invoke(ctx, "/Queue/TOIDReceiveToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueClient) TOIDUpdateNextQueue(ctx context.Context, in *RPCQueue, opts ...grpc.CallOption) (*RPCReply, error) {
	out := new(RPCReply)
	err := grpc.Invoke(ctx, "/Queue/TOIDUpdateNextQueue", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueClient) TOIDUpdateMaintainers(ctx context.Context, in *RPCMaintainers, opts ...grpc.CallOption) (*RPCReply, error) {
	out := new(RPCReply)
	err := grpc.Invoke(ctx, "/Queue/TOIDUpdateMaintainers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Queue service

type QueueServer interface {
	ReceiveRecords(context.Context, *RPCRecords) (*RPCReply, error)
	ReceiveToken(context.Context, *RPCToken) (*RPCReply, error)
	UpdateNextQueue(context.Context, *RPCQueue) (*RPCReply, error)
	UpdateMaintainers(context.Context, *RPCMaintainers) (*RPCReply, error)
	TOIDReceiveRecords(context.Context, *RPCRecords) (*RPCReply, error)
	TOIDReceiveToken(context.Context, *RPCTOIDToken) (*RPCReply, error)
	TOIDUpdateNextQueue(context.Context, *RPCQueue) (*RPCReply, error)
	TOIDUpdateMaintainers(context.Context, *RPCMaintainers) (*RPCReply, error)
}

func RegisterQueueServer(s *grpc.Server, srv QueueServer) {
	s.RegisterService(&_Queue_serviceDesc, srv)
}

func _Queue_ReceiveRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCRecords)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).ReceiveRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Queue/ReceiveRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).ReceiveRecords(ctx, req.(*RPCRecords))
	}
	return interceptor(ctx, in, info, handler)
}

func _Queue_ReceiveToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).ReceiveToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Queue/ReceiveToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).ReceiveToken(ctx, req.(*RPCToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _Queue_UpdateNextQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCQueue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).UpdateNextQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Queue/UpdateNextQueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).UpdateNextQueue(ctx, req.(*RPCQueue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Queue_UpdateMaintainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCMaintainers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).UpdateMaintainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Queue/UpdateMaintainers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).UpdateMaintainers(ctx, req.(*RPCMaintainers))
	}
	return interceptor(ctx, in, info, handler)
}

func _Queue_TOIDReceiveRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCRecords)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).TOIDReceiveRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Queue/TOIDReceiveRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).TOIDReceiveRecords(ctx, req.(*RPCRecords))
	}
	return interceptor(ctx, in, info, handler)
}

func _Queue_TOIDReceiveToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCTOIDToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).TOIDReceiveToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Queue/TOIDReceiveToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).TOIDReceiveToken(ctx, req.(*RPCTOIDToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _Queue_TOIDUpdateNextQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCQueue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).TOIDUpdateNextQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Queue/TOIDUpdateNextQueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).TOIDUpdateNextQueue(ctx, req.(*RPCQueue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Queue_TOIDUpdateMaintainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCMaintainers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).TOIDUpdateMaintainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Queue/TOIDUpdateMaintainers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).TOIDUpdateMaintainers(ctx, req.(*RPCMaintainers))
	}
	return interceptor(ctx, in, info, handler)
}

var _Queue_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Queue",
	HandlerType: (*QueueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveRecords",
			Handler:    _Queue_ReceiveRecords_Handler,
		},
		{
			MethodName: "ReceiveToken",
			Handler:    _Queue_ReceiveToken_Handler,
		},
		{
			MethodName: "UpdateNextQueue",
			Handler:    _Queue_UpdateNextQueue_Handler,
		},
		{
			MethodName: "UpdateMaintainers",
			Handler:    _Queue_UpdateMaintainers_Handler,
		},
		{
			MethodName: "TOIDReceiveRecords",
			Handler:    _Queue_TOIDReceiveRecords_Handler,
		},
		{
			MethodName: "TOIDReceiveToken",
			Handler:    _Queue_TOIDReceiveToken_Handler,
		},
		{
			MethodName: "TOIDUpdateNextQueue",
			Handler:    _Queue_TOIDUpdateNextQueue_Handler,
		},
		{
			MethodName: "TOIDUpdateMaintainers",
			Handler:    _Queue_TOIDUpdateMaintainers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "queue/queue.proto",
}

func init() { proto.RegisterFile("queue/queue.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 551 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xfd, 0x6c, 0x37, 0x49, 0x3d, 0x69, 0x92, 0x76, 0xbf, 0x82, 0x56, 0x15, 0x42, 0x96, 0x55,
	0x21, 0x03, 0xc2, 0x88, 0xf0, 0xab, 0xde, 0xa1, 0xc0, 0x45, 0x10, 0xd0, 0xb0, 0x0a, 0x0f, 0xb0,
	0xc4, 0x43, 0x58, 0xd5, 0xb1, 0x83, 0x77, 0x13, 0x25, 0x4f, 0xc5, 0x23, 0x82, 0x76, 0xed, 0xb5,
	0x13, 0x90, 0xaa, 0xdc, 0x58, 0x73, 0x66, 0xce, 0xee, 0x9c, 0x99, 0x63, 0x1b, 0xce, 0x7e, 0xae,
	0x70, 0x85, 0x4f, 0xcd, 0x33, 0x5e, 0x16, 0xb9, 0xca, 0xc3, 0x5f, 0x2e, 0xf8, 0x6c, 0x32, 0x62,
	0x38, 0xcb, 0x8b, 0x84, 0xf4, 0xc1, 0x15, 0x09, 0x75, 0x02, 0x27, 0xf2, 0x99, 0x2b, 0x12, 0x72,
	0x0f, 0x7c, 0x25, 0x16, 0x28, 0x15, 0x5f, 0x2c, 0xa9, 0x1b, 0x38, 0x91, 0xc7, 0x9a, 0x04, 0x21,
	0x70, 0xf4, 0x23, 0x97, 0x8a, 0x7a, 0x81, 0x13, 0xf5, 0x98, 0x89, 0xc9, 0x29, 0x78, 0xa9, 0x48,
	0xe8, 0x91, 0x49, 0xe9, 0x90, 0x44, 0x70, 0xa4, 0xf8, 0x5c, 0xd2, 0x56, 0xe0, 0x45, 0xdd, 0xe1,
	0x79, 0x5c, 0x77, 0x8b, 0xa7, 0x7c, 0x2e, 0xdf, 0x67, 0xaa, 0xd8, 0x32, 0xc3, 0x20, 0x77, 0xa1,
	0xbd, 0xe4, 0x05, 0x66, 0x8a, 0xb6, 0x03, 0x2f, 0xf2, 0x59, 0x85, 0x74, 0x1f, 0x89, 0x98, 0xd0,
	0x8e, 0xd1, 0x65, 0x62, 0x9d, 0x53, 0xb9, 0x48, 0xe8, 0x71, 0xd9, 0x5b, 0xc7, 0xe4, 0x31, 0xf8,
	0x33, 0xbe, 0x92, 0x3c, 0x15, 0x6a, 0x4b, 0xfd, 0xc0, 0x89, 0xba, 0xc3, 0x9e, 0x6e, 0x37, 0xb2,
	0x49, 0xd6, 0xd4, 0x2f, 0x5e, 0x83, 0x5f, 0xf7, 0xd7, 0xaa, 0x6f, 0x70, 0x5b, 0x0d, 0xae, 0x43,
	0x72, 0x0e, 0xad, 0x35, 0x4f, 0x57, 0x68, 0xa6, 0xf6, 0x59, 0x09, 0xae, 0xdc, 0x37, 0x4e, 0xf8,
	0x0a, 0x4e, 0x76, 0xef, 0xac, 0xb7, 0xe0, 0xec, 0x6c, 0xc1, 0xaa, 0x73, 0x1b, 0x75, 0xe1, 0x10,
	0xa0, 0x1e, 0x5d, 0x92, 0x4b, 0xe8, 0x14, 0x65, 0x48, 0x1d, 0xb3, 0x18, 0x68, 0x16, 0xc3, 0x6c,
	0x29, 0xbc, 0x84, 0x63, 0x93, 0x5d, 0xa6, 0x5b, 0x42, 0xa1, 0xb3, 0x40, 0x29, 0xf9, 0x1c, 0x2b,
	0x9d, 0x16, 0x86, 0x57, 0x86, 0xf5, 0x45, 0xbb, 0xaa, 0x59, 0x6b, 0x2c, 0xa4, 0xc8, 0xb3, 0x4a,
	0x90, 0x85, 0x7a, 0x22, 0x63, 0xbc, 0x9d, 0xc8, 0x80, 0xaa, 0xc3, 0x34, 0xbf, 0xc1, 0x4c, 0x9f,
	0x4d, 0xb9, 0x54, 0x69, 0xf5, 0x0a, 0xf4, 0x98, 0x85, 0xe1, 0x07, 0xe8, 0xb3, 0xc9, 0xe8, 0x13,
	0x17, 0x99, 0xe2, 0x22, 0xc3, 0x42, 0xde, 0xd2, 0xe7, 0x3e, 0xc0, 0xa2, 0x26, 0x52, 0xd7, 0x38,
	0xb9, 0x93, 0x09, 0xdf, 0x42, 0x97, 0x4d, 0x46, 0xe3, 0x2c, 0xc1, 0xcd, 0xed, 0x17, 0x51, 0xe8,
	0x88, 0x92, 0x55, 0xdd, 0x62, 0x61, 0xb8, 0x31, 0x16, 0x4c, 0xaf, 0xc7, 0xef, 0x6a, 0xe1, 0x0b,
	0xbe, 0x99, 0x5e, 0x8f, 0x13, 0xb3, 0xcc, 0x1e, 0xb3, 0xd0, 0x8e, 0xf4, 0x71, 0x6c, 0xbd, 0xb0,
	0x90, 0xbc, 0x80, 0x41, 0x82, 0xdf, 0xb1, 0x28, 0x30, 0xa9, 0x3c, 0xa1, 0xde, 0x3f, 0x46, 0xfc,
	0x4d, 0x19, 0xfe, 0x76, 0xa1, 0x55, 0x2e, 0xfa, 0x11, 0xf4, 0x19, 0xce, 0x50, 0xac, 0xd1, 0x5a,
	0xda, 0x6d, 0x0e, 0xca, 0x0b, 0x3f, 0xb6, 0xc6, 0x85, 0xff, 0x91, 0x07, 0x70, 0x52, 0x71, 0x4b,
	0xbd, 0xa6, 0x68, 0xc2, 0x7d, 0xde, 0x43, 0x18, 0x7c, 0x5d, 0x26, 0x5c, 0xe1, 0x67, 0xdc, 0xa8,
	0xb2, 0x8d, 0xa9, 0x9b, 0x70, 0x9f, 0xfa, 0x0c, 0xce, 0x4a, 0xea, 0xae, 0x29, 0x83, 0x78, 0xdf,
	0xa5, 0xfd, 0x23, 0x31, 0x10, 0xbd, 0xb2, 0x83, 0x55, 0xc7, 0x70, 0xba, 0xc3, 0x2f, 0x95, 0x9b,
	0xef, 0xa9, 0x5e, 0xfc, 0x3e, 0xff, 0x09, 0xfc, 0xaf, 0x2b, 0x87, 0x4e, 0xf0, 0x12, 0xee, 0x34,
	0xf4, 0x83, 0xa7, 0xf8, 0xd6, 0x36, 0xff, 0xad, 0xe7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x06,
	0x3b, 0xc7, 0x71, 0xcc, 0x04, 0x00, 0x00,
}
