// Code generated by protoc-gen-go. DO NOT EDIT.
// source: queue/queue.proto

/*
Package queue is a generated protocol buffer package.

It is generated from these files:
	queue/queue.proto

It has these top-level messages:
	RPCRecord
	RPCRecords
	RPCReply
	RPCQueue
	RPCToken
	RPCMaintainers
	RPCIndexers
*/
package queue

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RPCRecord struct {
	Timestamp int64             `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Host      int32             `protobuf:"varint,2,opt,name=host" json:"host,omitempty"`
	Lid       int32             `protobuf:"varint,3,opt,name=lid" json:"lid,omitempty"`
	Tags      map[string]string `protobuf:"bytes,4,rep,name=tags" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Hash      []uint64          `protobuf:"varint,5,rep,packed,name=hash" json:"hash,omitempty"`
	Seed      uint64            `protobuf:"varint,6,opt,name=seed" json:"seed,omitempty"`
}

func (m *RPCRecord) Reset()                    { *m = RPCRecord{} }
func (m *RPCRecord) String() string            { return proto.CompactTextString(m) }
func (*RPCRecord) ProtoMessage()               {}
func (*RPCRecord) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RPCRecord) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RPCRecord) GetHost() int32 {
	if m != nil {
		return m.Host
	}
	return 0
}

func (m *RPCRecord) GetLid() int32 {
	if m != nil {
		return m.Lid
	}
	return 0
}

func (m *RPCRecord) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *RPCRecord) GetHash() []uint64 {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *RPCRecord) GetSeed() uint64 {
	if m != nil {
		return m.Seed
	}
	return 0
}

type RPCRecords struct {
	Records []*RPCRecord `protobuf:"bytes,1,rep,name=records" json:"records,omitempty"`
}

func (m *RPCRecords) Reset()                    { *m = RPCRecords{} }
func (m *RPCRecords) String() string            { return proto.CompactTextString(m) }
func (*RPCRecords) ProtoMessage()               {}
func (*RPCRecords) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RPCRecords) GetRecords() []*RPCRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

type RPCReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *RPCReply) Reset()                    { *m = RPCReply{} }
func (m *RPCReply) String() string            { return proto.CompactTextString(m) }
func (*RPCReply) ProtoMessage()               {}
func (*RPCReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RPCReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RPCQueue struct {
	Version int32  `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Queue   string `protobuf:"bytes,2,opt,name=queue" json:"queue,omitempty"`
}

func (m *RPCQueue) Reset()                    { *m = RPCQueue{} }
func (m *RPCQueue) String() string            { return proto.CompactTextString(m) }
func (*RPCQueue) ProtoMessage()               {}
func (*RPCQueue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RPCQueue) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *RPCQueue) GetQueue() string {
	if m != nil {
		return m.Queue
	}
	return ""
}

type RPCToken struct {
	Lastlid int32 `protobuf:"varint,1,opt,name=lastlid" json:"lastlid,omitempty"`
}

func (m *RPCToken) Reset()                    { *m = RPCToken{} }
func (m *RPCToken) String() string            { return proto.CompactTextString(m) }
func (*RPCToken) ProtoMessage()               {}
func (*RPCToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RPCToken) GetLastlid() int32 {
	if m != nil {
		return m.Lastlid
	}
	return 0
}

type RPCMaintainers struct {
	Version    int32    `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Maintainer []string `protobuf:"bytes,2,rep,name=maintainer" json:"maintainer,omitempty"`
}

func (m *RPCMaintainers) Reset()                    { *m = RPCMaintainers{} }
func (m *RPCMaintainers) String() string            { return proto.CompactTextString(m) }
func (*RPCMaintainers) ProtoMessage()               {}
func (*RPCMaintainers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RPCMaintainers) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *RPCMaintainers) GetMaintainer() []string {
	if m != nil {
		return m.Maintainer
	}
	return nil
}

type RPCIndexers struct {
	Version int32    `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Indexer []string `protobuf:"bytes,2,rep,name=indexer" json:"indexer,omitempty"`
}

func (m *RPCIndexers) Reset()                    { *m = RPCIndexers{} }
func (m *RPCIndexers) String() string            { return proto.CompactTextString(m) }
func (*RPCIndexers) ProtoMessage()               {}
func (*RPCIndexers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RPCIndexers) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *RPCIndexers) GetIndexer() []string {
	if m != nil {
		return m.Indexer
	}
	return nil
}

func init() {
	proto.RegisterType((*RPCRecord)(nil), "RPCRecord")
	proto.RegisterType((*RPCRecords)(nil), "RPCRecords")
	proto.RegisterType((*RPCReply)(nil), "RPCReply")
	proto.RegisterType((*RPCQueue)(nil), "RPCQueue")
	proto.RegisterType((*RPCToken)(nil), "RPCToken")
	proto.RegisterType((*RPCMaintainers)(nil), "RPCMaintainers")
	proto.RegisterType((*RPCIndexers)(nil), "RPCIndexers")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Queue service

type QueueClient interface {
	ReceiveRecords(ctx context.Context, in *RPCRecords, opts ...grpc.CallOption) (*RPCReply, error)
	ReceiveToken(ctx context.Context, in *RPCToken, opts ...grpc.CallOption) (*RPCReply, error)
	UpdateNextQueue(ctx context.Context, in *RPCQueue, opts ...grpc.CallOption) (*RPCReply, error)
	UpdateMaintainers(ctx context.Context, in *RPCMaintainers, opts ...grpc.CallOption) (*RPCReply, error)
	UpdateIndexers(ctx context.Context, in *RPCIndexers, opts ...grpc.CallOption) (*RPCReply, error)
}

type queueClient struct {
	cc *grpc.ClientConn
}

func NewQueueClient(cc *grpc.ClientConn) QueueClient {
	return &queueClient{cc}
}

func (c *queueClient) ReceiveRecords(ctx context.Context, in *RPCRecords, opts ...grpc.CallOption) (*RPCReply, error) {
	out := new(RPCReply)
	err := grpc.Invoke(ctx, "/Queue/ReceiveRecords", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueClient) ReceiveToken(ctx context.Context, in *RPCToken, opts ...grpc.CallOption) (*RPCReply, error) {
	out := new(RPCReply)
	err := grpc.Invoke(ctx, "/Queue/ReceiveToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueClient) UpdateNextQueue(ctx context.Context, in *RPCQueue, opts ...grpc.CallOption) (*RPCReply, error) {
	out := new(RPCReply)
	err := grpc.Invoke(ctx, "/Queue/UpdateNextQueue", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueClient) UpdateMaintainers(ctx context.Context, in *RPCMaintainers, opts ...grpc.CallOption) (*RPCReply, error) {
	out := new(RPCReply)
	err := grpc.Invoke(ctx, "/Queue/UpdateMaintainers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueClient) UpdateIndexers(ctx context.Context, in *RPCIndexers, opts ...grpc.CallOption) (*RPCReply, error) {
	out := new(RPCReply)
	err := grpc.Invoke(ctx, "/Queue/UpdateIndexers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Queue service

type QueueServer interface {
	ReceiveRecords(context.Context, *RPCRecords) (*RPCReply, error)
	ReceiveToken(context.Context, *RPCToken) (*RPCReply, error)
	UpdateNextQueue(context.Context, *RPCQueue) (*RPCReply, error)
	UpdateMaintainers(context.Context, *RPCMaintainers) (*RPCReply, error)
	UpdateIndexers(context.Context, *RPCIndexers) (*RPCReply, error)
}

func RegisterQueueServer(s *grpc.Server, srv QueueServer) {
	s.RegisterService(&_Queue_serviceDesc, srv)
}

func _Queue_ReceiveRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCRecords)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).ReceiveRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Queue/ReceiveRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).ReceiveRecords(ctx, req.(*RPCRecords))
	}
	return interceptor(ctx, in, info, handler)
}

func _Queue_ReceiveToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).ReceiveToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Queue/ReceiveToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).ReceiveToken(ctx, req.(*RPCToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _Queue_UpdateNextQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCQueue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).UpdateNextQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Queue/UpdateNextQueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).UpdateNextQueue(ctx, req.(*RPCQueue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Queue_UpdateMaintainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCMaintainers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).UpdateMaintainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Queue/UpdateMaintainers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).UpdateMaintainers(ctx, req.(*RPCMaintainers))
	}
	return interceptor(ctx, in, info, handler)
}

func _Queue_UpdateIndexers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCIndexers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).UpdateIndexers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Queue/UpdateIndexers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).UpdateIndexers(ctx, req.(*RPCIndexers))
	}
	return interceptor(ctx, in, info, handler)
}

var _Queue_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Queue",
	HandlerType: (*QueueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveRecords",
			Handler:    _Queue_ReceiveRecords_Handler,
		},
		{
			MethodName: "ReceiveToken",
			Handler:    _Queue_ReceiveToken_Handler,
		},
		{
			MethodName: "UpdateNextQueue",
			Handler:    _Queue_UpdateNextQueue_Handler,
		},
		{
			MethodName: "UpdateMaintainers",
			Handler:    _Queue_UpdateMaintainers_Handler,
		},
		{
			MethodName: "UpdateIndexers",
			Handler:    _Queue_UpdateIndexers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "queue/queue.proto",
}

func init() { proto.RegisterFile("queue/queue.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x53, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0xed, 0x5a, 0x52, 0x5c, 0x8d, 0x83, 0xd3, 0x2c, 0x39, 0x2c, 0xa1, 0x14, 0x21, 0x42, 0x51,
	0x5b, 0x50, 0xa9, 0x7b, 0x68, 0xc9, 0xad, 0x98, 0x1e, 0x5a, 0x68, 0x71, 0x97, 0xf4, 0x07, 0x6c,
	0xa3, 0xc1, 0x11, 0xd1, 0x57, 0xb5, 0x6b, 0x63, 0xff, 0xd5, 0xfe, 0x80, 0xfe, 0x8e, 0xb0, 0xb3,
	0x92, 0x6c, 0x5d, 0x7c, 0x11, 0x6f, 0x66, 0xde, 0xcc, 0x7b, 0xfb, 0x40, 0x70, 0xf9, 0x77, 0x83,
	0x1b, 0x7c, 0x4f, 0xdf, 0xb4, 0x69, 0x6b, 0x53, 0xc7, 0xff, 0x18, 0x84, 0x72, 0xb5, 0x94, 0x78,
	0x5f, 0xb7, 0x19, 0x7f, 0x09, 0xa1, 0xc9, 0x4b, 0xd4, 0x46, 0x95, 0x8d, 0x60, 0x11, 0x4b, 0x3c,
	0x79, 0x68, 0x70, 0x0e, 0xfe, 0x43, 0xad, 0x8d, 0x98, 0x44, 0x2c, 0x09, 0x24, 0x61, 0xfe, 0x02,
	0xbc, 0x22, 0xcf, 0x84, 0x47, 0x2d, 0x0b, 0x79, 0x02, 0xbe, 0x51, 0x6b, 0x2d, 0xfc, 0xc8, 0x4b,
	0x66, 0x8b, 0xab, 0x74, 0xb8, 0x9e, 0xde, 0xa9, 0xb5, 0xfe, 0x5a, 0x99, 0x76, 0x2f, 0x89, 0x41,
	0xf7, 0x94, 0x7e, 0x10, 0x41, 0xe4, 0x25, 0xbe, 0x24, 0x6c, 0x7b, 0x1a, 0x31, 0x13, 0x67, 0x11,
	0xb3, 0x3d, 0x8b, 0xaf, 0x3f, 0x41, 0x38, 0xac, 0x5a, 0xc1, 0x47, 0xdc, 0x93, 0xb9, 0x50, 0x5a,
	0xc8, 0xaf, 0x20, 0xd8, 0xaa, 0x62, 0x83, 0xe4, 0x2b, 0x94, 0xae, 0xb8, 0x9d, 0x7c, 0x66, 0xf1,
	0x02, 0x60, 0x50, 0xd7, 0xfc, 0x06, 0xa6, 0xad, 0x83, 0x82, 0x91, 0x37, 0x38, 0x78, 0x93, 0xfd,
	0x28, 0xbe, 0x81, 0xe7, 0xd4, 0x6d, 0x8a, 0x3d, 0x17, 0x30, 0x2d, 0x51, 0x6b, 0xb5, 0xc6, 0x4e,
	0xaf, 0x2f, 0xe3, 0x5b, 0x62, 0xfd, 0xb2, 0x41, 0x5a, 0xd6, 0x16, 0x5b, 0x9d, 0xd7, 0x15, 0xb1,
	0x02, 0xd9, 0x97, 0xd6, 0x19, 0x65, 0xdd, 0x3b, 0xa3, 0xa2, 0x53, 0xb8, 0xab, 0x1f, 0xb1, 0xb2,
	0xbb, 0x85, 0xd2, 0xc6, 0x46, 0xd8, 0xed, 0x76, 0x65, 0xfc, 0x1d, 0xe6, 0x72, 0xb5, 0xfc, 0xa1,
	0xf2, 0xca, 0xa8, 0xbc, 0xc2, 0x56, 0x9f, 0xd0, 0x79, 0x05, 0x50, 0x0e, 0x44, 0x31, 0x89, 0xbc,
	0x24, 0x94, 0x47, 0x9d, 0xf8, 0x0b, 0xcc, 0xe4, 0x6a, 0xf9, 0xad, 0xca, 0x70, 0x77, 0xfa, 0x90,
	0x80, 0x69, 0xee, 0x58, 0xdd, 0x95, 0xbe, 0x5c, 0xfc, 0x67, 0x10, 0xb8, 0xe7, 0xbe, 0x85, 0xb9,
	0xc4, 0x7b, 0xcc, 0xb7, 0xd8, 0x07, 0x3b, 0x3b, 0xe4, 0xa8, 0xaf, 0xc3, 0xb4, 0x8f, 0x2f, 0x7e,
	0xc6, 0x5f, 0xc3, 0x79, 0xc7, 0x75, 0xcf, 0xa5, 0x21, 0xc1, 0x31, 0xef, 0x0d, 0x5c, 0xfc, 0x6e,
	0x32, 0x65, 0xf0, 0x27, 0xee, 0x8c, 0x93, 0xa1, 0x39, 0xc1, 0x31, 0xf5, 0x03, 0x5c, 0x3a, 0xea,
	0x71, 0x34, 0x17, 0xe9, 0x38, 0xab, 0xf1, 0xca, 0x3b, 0x98, 0xbb, 0x95, 0x21, 0x81, 0xf3, 0xf4,
	0x28, 0x8f, 0x11, 0xf9, 0xcf, 0x19, 0xfd, 0x17, 0x1f, 0x9f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x91,
	0xdd, 0x15, 0x21, 0x2c, 0x03, 0x00, 0x00,
}
